FROM ubuntu:noble

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libreadline8t64 libtcl8.6 \
        libboost-program-options1.83.0 libboost-thread1.83.0 libboost-filesystem1.83.0 \
        libpython3.12t64 \
        python3-pip

RUN pip install --no-cache-dir --break-system-packages --upgrade amaranth
